In [3]:
import pandas as pd
df = pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [5]:
df = df.set_index('Name', drop = True)
print(df)

                                                    PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   
...                                                         ...       ...   
Montvila, Rev. Juozas                                       887         0   
Graham, Miss. Margaret Edith                                888         1   
Johnston, Miss. Catherine Helen "Carrie"                    889         0   
Behr, Mr. Karl Howell                                       890         1   
Dooley, Mr. Patrick                                         891         0   

In [7]:
df.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                   22
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [8]:
df.loc['Braund, Mr. Owen Harris':'Dooley, Mr. Patrick',:'Ticket']

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket
Name,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450
...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607


In [9]:
df['child']=df['Parch']+df['SibSp']

In [12]:
df.loc['Braund, Mr. Owen Harris':'Dooley, Mr. Patrick',:]


,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,child
Name,,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,1
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S,0
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S,0
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3


In [29]:
import numpy as np
n = np.random.randint(1,100,(8,5))
print(n)
print(n.shape)
print(n.size)
print(n.ndim)

# x= np.concatenate(n, axis=0)
# x = np.sum(n, axis=0)
# print(x)

df = pd.DataFrame(n,columns=['a','b','c','d','e'])
df['sum'] = df['a']+df['b']+df['c']+df['d']+df['e']
df.loc[6,2]=7
df.loc[5:7,'b':'d']
df.loc[9]=[50,60,70,80,90,100,110]
print(df)

[[ 4 14 13  7 19]
 [45  5  2 76 40]
 [14 79 93 69 26]
 [ 1 46 62 68 99]
 [85 48 75 76 26]
 [33 96 33 89 61]
 [59 55 65  7 97]
 [39 85 34 23 56]]
(8, 5)
40
2
    a   b   c   d   e  sum      2
0   4  14  13   7  19   57    NaN
1  45   5   2  76  40  168    NaN
2  14  79  93  69  26  281    NaN
3   1  46  62  68  99  276    NaN
4  85  48  75  76  26  310    NaN
5  33  96  33  89  61  312    NaN
6  59  55  65   7  97  283    7.0
7  39  85  34  23  56  237    NaN
9  50  60  70  80  90  100  110.0


In [31]:
df = pd.DataFrame(np.random.randint(1,100,(5,4)), columns = ['courseid','courseName','credits','faculty'])
print(df)

   courseid  courseName  credits  faculty
0        63          38       73       36
1        37          23       35       30
2        48          92       17       36
3        46          49       68        7
4        98          75       75       80


In [34]:
df.head()

,courseid,courseName,credits,faculty
0,63,38,73,36


In [37]:
df.tail()

,courseid,courseName,credits,faculty
0,63,38,73,36
1,37,23,35,30
2,48,92,17,36
3,46,49,68,7
4,98,75,75,80


In [38]:
df.tail(4)

,courseid,courseName,credits,faculty
1,37,23,35,30
2,48,92,17,36
3,46,49,68,7
4,98,75,75,80


In [39]:
df.sample()

,courseid,courseName,credits,faculty
0,63,38,73,36


In [40]:
df.sample(5)
# random data

,courseid,courseName,credits,faculty
2,48,92,17,36
1,37,23,35,30
0,63,38,73,36
4,98,75,75,80
3,46,49,68,7


In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   courseid    5 non-null      int32
 1   courseName  5 non-null      int32
 2   credits     5 non-null      int32
 3   faculty     5 non-null      int32
dtypes: int32(4)
memory usage: 208.0 bytes


In [42]:
df.describe()

,courseid,courseName,credits,faculty
count,5.000000,5.000000,5.0000,5.00000
mean,58.400000,55.400000,53.6000,37.80000
std,24.027068,27.915945,26.1113,26.44239
min,37.000000,23.000000,17.0000,7.00000
25%,46.000000,38.000000,35.0000,30.00000
50%,48.000000,49.000000,68.0000,36.00000
75%,63.000000,75.000000,73.0000,36.00000
max,98.000000,92.000000,75.0000,80.00000


In [45]:
df.describe(include='all')

,courseid,courseName,credits,faculty
count,5.000000,5.000000,5.0000,5.00000
mean,58.400000,55.400000,53.6000,37.80000
std,24.027068,27.915945,26.1113,26.44239
min,37.000000,23.000000,17.0000,7.00000
25%,46.000000,38.000000,35.0000,30.00000
50%,48.000000,49.000000,68.0000,36.00000
75%,63.000000,75.000000,73.0000,36.00000
max,98.000000,92.000000,75.0000,80.00000
